# Generated by Django 3.0.5 on 2020-05-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Notes',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='notes',
            new_name='note_link',
        ),
    ]
