# Generated by Django 3.0.5 on 2020-05-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200528_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
