# Generated by Django 3.0.5 on 2020-05-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_notes_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='note_link',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(max_length=450),
        ),
    ]
