# Generated by Django 3.0.5 on 2020-05-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20200530_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='time_stamp',
        ),
    ]
